name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
     matrix:
      operating-system: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: cd src; dotnet restore
    - name: Build
      run: cd src; dotnet build --configuration Release --no-restore
    - name: Test
      run: cd src; dotnet test --no-restore --verbosity normal

    - name: Install examples dependencies
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/chrisg2/index.json -n github -u chrisg2 -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        cd examples
        dotnet restore
    - name: Build examples
      run: cd examples; dotnet build --configuration Release --no-restore
    - name: Test examples
      run: cd examples; dotnet test --no-restore --verbosity normal
