name: Test Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
     matrix:
      operating-system: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/chrisg2/index.json -n github -u chrisg2 -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet restore examples/*sln
    - name: Build
      run: dotnet build --configuration Release --no-restore examples/*sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal examples/*sln
    - name: Test SnapTest.Examples
      run: dotnet run --configuration Release --no-build --verbosity normal --project examples/SnapTest.Examples/*csproj
